name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make unzip gcc ripgrep

      - name: Install Neovim
        run: |
          curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
          tar -xzf nvim-linux64.tar.gz
          sudo mv nvim-linux64 /opt/nvim
          sudo ln -sf /opt/nvim/bin/nvim /usr/local/bin/nvim
          nvim --version

      - name: Install stylua
        run: |
          curl -L https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip -o stylua.zip
          unzip stylua.zip
          chmod +x stylua
          sudo mv stylua /usr/local/bin/

      - name: Install plugins
        run: |
          nvim --headless -c "qall" || true
          nvim --headless -c "lua require('lazy').install({wait = true})" -c "qall"

      - name: Run health check
        run: make health

      - name: Run tests
        run: make test